### PR TITLE
New architecture support

### PR DESCRIPTION
**Pull request by haileyok**

### CODE REVIEW

**Comment by MicroDroid** [comment]
Is this usable by now? I want to copy off some of this library's code to another library

**Comment by haileyok** [comment]
@MicroDroid Sorry, just now seeing this. The example is mostly working, but my intention is to wrap this work this week. I can ping you again when I get it wrapped.

**Comment by MicroDroid** [comment]
No worries :) Yeah I'd appreciate a ping 👍

**Comment by haileyok** [comment]
@MicroDroid Hey, I merged this work in. It's not super tested yet, though everything appears to be working in the example app...going to work on getting it moved into our app at some point here this week and will start working out kinks at that point.

**Comment by MicroDroid** [comment]
wow that was fast, I'll try it out and let you know if something is broken (cause I tried this before the recent changes, and something was)👍

thanks either way :)

**Pull request merged**
